### ISSUE TITLE
Browsers?

### ISSUE THREAD

**Issue by briannyeko** [LedgerHQ/ledger-wallet-chrome#15]
When will the ledger wallet work with other browsers like brave,firefox and opera?

And when will you add Dogecoin & Litecoin to the ledger wallet? Will it work with all HD wallets that you offer?

**Comment by pollastri-pierre** [comment]
Hello,

Currently we can only work on Chromium because it's the only browser with a USB API. We will probably release a "stand-alone" application which doesn't rely on any browser in the future.

We don't know yet when we will release a wallet application for Dogecoin or Litecoin but the Ledger Wallet can already deal with these currencies. We just don't provide a wallet chrome application currently.
