### ISSUE TITLE
Unable to validate transaction

### ISSUE THREAD

**Issue by andrehortabh** [LedgerHQ/ledger-wallet-chrome#41]
Unable to send BCC. Message: "Unabled to validate transaction when try to send Bitcoin Cash". It is impossible to send BCC in Ledger. I tried to use a lot of computer, remove and install chrome app, but not solved.

![image](https://user-images.githubusercontent.com/11886676/28938778-6ffcfdb0-7865-11e7-9686-48419e315357.png)

**Comment by btchip** [comment]
Verify that you're using the Bitcoin Cash app on the device.

**Comment by andrehortabh** [comment]
Yes, I choosed Bitcoin Cash - Main

**Comment by btchip** [comment]
I'm talking about the application on the device. You need to load the
"Bitcoin Cash" app from Ledger Manager

**Comment by andrehortabh** [comment]
Understood. At Ledger Manager there is no Bitcoin Cash application. Have only: Bitcoin, Dash, Dogecoin, Ethereum, Fido U2F, Litecoin, Stratis e ZCash.

**Comment by btchip** [comment]
Update to firmware 1.3.1 first. Also read our Medium post

**Comment by andrehortabh** [comment]
I will lost my Bicoin Cash updating firmware?

**Comment by btchip** [comment]
No. Read our Medium post before proceeding

On Aug 3, 2017 9:34 PM, "andrehortabh" <notifications@github.com> wrote:

I will lost my Bicoin Cash updating firmware?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/LedgerHQ/ledger-wallet-chrome/issues/41#issuecomment-320068283>,
or mute the thread

**Comment by andrehortabh** [comment]
Thank you! Sorry about that (put a message: you need to update your firmware to use bitcoin cash)
