### ISSUE TITLE
1.3.6 completely removes the Coinkite app

### ISSUE THREAD

**Issue by aussiehash** [LedgerHQ/ledger-wallet-chrome#7]
v1.2.0 had a lovely coinkite app, with the functions

* Test Nano
* Go to Coinkite
* Export Key
* Cosign Transaction

This app has completely dissapeared from 1.3.6

**Comment by EricLarch** [comment]
Ledger is now integrated directly from the coinkite web application, and the Coinkite app is not necessary anymore (deprecated).

You can see more information here:
https://ledger.groovehq.com/knowledge_base/topics/how-to-use-the-ledger-nano-with-coinkite-multisignature

**Comment by aussiehash** [comment]
I can now see all versions > 1.2.0 have the Coinkite app removed.

This "new" method is as simple a one-click  -- in line with other ease of use choices you've made for Nano like a 4-digit-PIN, 2fa card instead of HID replay confirmation, future firmware upgrades wont wipe the seed, Chrome-only initialization (no user or device entropy, no offline command line initialization)

However I strongly believe removing the "old" cosign method reduces Coinkite + Ledger Multisig to a mere proof of concept, rather than an enterprise grade multisig option.

There is no redundancy.  Coinkite provides a full UTXO report, and if their service disappears I could still manually retrieve my funds.

With your the "old" method, I could use the btchip-c-api / python-api / bitmex scripts and offline co-sign the transaction.  

With this "new" method, if a future Chrome update breaks something, or if Ledger's home server goes offline then it will be impossible to cosign.  A single point of failure.  How could I trust my life's savings on the uptime of Ledger's server ?  This is even worse than case wallet's multisig.

At least Trezor is not dependent on myTrezor (who's BoP server crashes intermittently). One can still use mycelium/electrum or a BIP32 calculator to retrieve my funds.

All is not lost - Ledger Chrome 1.3.6 still supports fw 1.4.13, which includes winUSB.  I'm unable to compile unified firmware updated btchip-c-api binaries, and removing winUSB breaks pyusb compatibility for me.  With this older firmware, and reverting `/views/wallet/settings/app/list.js`, I am able to coinkite multisig online with "Import BIP32 xpub", sign from Ledger chrome wallet via the coinkite app with the backup option of offline BitMEX signing from the command line as disaster recovery.

I hope you will consider officially adding back the coinkite beta app, or offering it as a stand alone chrome app and/or HTML tool.  It will also be necessary to provide an easy firmware downgrade path for those who do wish to more easily manage their HW-1/Nano from the command line.

**Comment by btchip** [comment]
> I can now see all versions > 1.2.0 have the Coinkite app removed.

Yes because as it's not necessary to have it in. Not because we removed anything.

> This "new" method is as simple a one-click 

you still need to enter a PIN to unlock the device - the choice we made for all multisignature implementations (such as GreenAddress) is that it's up to another co-signing party to check the validity of the transaction until we have a device allowing to do that easily.

Other choices have been taken to make the device easier to use, while not compromising on security, or even improving it. Besides, power users can still choose to use the older methods if they wish to do so.

>in line with other ease of use choices you've made for Nano like a 4-digit-PIN, 

The chip supports up to 32 digits PINs. 4 digits is the de-facto standard for EMV (banking) and SIM cards, also the chip is wiped after 3 wrong attempts.

> 2fa card instead of HID replay confirmation

HID replay confirmation can still be used through the API. It is indeed better than the 2fa card, but not convenient as you'd need to have another device nearby to use it in a secure way. Also the mobile phone validation is way better and more convenient than HID replay or the 2fa card.

> future firmware upgrades wont wipe the seed, 

It makes the device more convenient and more secure to use as you don't have to go through the live CD boot cycle every time you plan to upgrade the firmware. 

> Chrome-only initialization (no user or device entropy, no offline command line initialization)

you can still initialize it offline with the API or the Live CD we'll provide. You can provide your own entropy by providing your own seed.

> However I strongly believe removing the "old" cosign method reduces Coinkite + Ledger Multisig to a mere proof of concept, rather than an enterprise grade multisig option.

It doesn't change anything. It just moves the app back to Coinkite where it belongs.

>There is no redundancy. Coinkite provides a full UTXO report, and if their service disappears I could still manually retrieve my funds.

>With your the "old" method, I could use the btchip-c-api / python-api / bitmex scripts and offline co-sign the transaction.

you can still do that. Absolutely nothing has changed. When using the command line tools you just need to start the derivation from the path we arbitrary chose in https://github.com/LedgerHQ/ledger-wallet-chrome/blob/master/app/src/utils/apps/coinkite.coffee (0xb11e'/0xccc0') or 45342h/52416h if using a different notation. Exactly the same as before. 

> With this "new" method, if a future Chrome update breaks something, or if Ledger's home server goes offline then it will be impossible to cosign. A single point of failure. How could I trust my life's savings on the uptime of Ledger's server ? This is even worse than case wallet's multisig.

I think you'll revise this considering what I said before

Besides, the old application didn't change anything there - it was still bound to the wallet, and couldn't start if you couldn't open the wallet.

 > At least Trezor is not dependent on myTrezor (who's BoP server crashes intermittently). One can still use mycelium/electrum or a BIP32 calculator to retrieve my funds.

You can do exactly the same here. 

Of course if you lock funds in a multisignature then all parties need to collaborate.

> All is not lost - Ledger Chrome 1.3.6 still supports fw 1.4.13, which includes winUSB. I'm unable to compile unified firmware updated btchip-c-api binaries, and removing winUSB breaks pyusb compatibility for me. 

1.4.13 is deprecated, and we don't advise anyone to keep using it. The WinUSB issues are unfortunate and the way to fix them properly would be to make the C API build process better to handle your specific build issues (which would solve both the C and Python problems), not going back to WinUSB. I'll have another member of our team talk to you, he also had some issues building HIDAPI in his environment, solved them last week and can likely help.

> I hope you will consider officially adding back the coinkite beta app, or offering it as a stand alone chrome app and/or HTML tool

The right way to do it would be to merge it with Coinkite offline recovery tool, or at least add a section in the tutorial pointing to Bitmex. We'll be adding that.

> It will also be necessary to provide an easy firmware downgrade path for those who do wish to more easily manage their HW-1/Nano from the command line.

The right way to do that would be to understand and fix the issues of the command line tools with the latest version, everything is designed to be backward compatible and supposed to stay that way. Note that this doesn't include WINUSB support, but there's really no technical reason for any platform to support this and not HID.

**Comment by aussiehash** [comment]
>>However I strongly believe removing the "old" cosign method reduces Coinkite + Ledger Multisig to a mere proof of concept, rather than an enterprise grade multisig option.

>It doesn't change anything. It just moves the app back to Coinkite where it belongs.

There is a significant difference in the engineering.  The old method relied only on Coinkite's server to be up (and even then one could pre-download the unsigned .json files, or manually build one's own transaction from the UTXO report).

In the "old" method Ledger Wallet queried the **Coinkite Server** via CK's API, requiring the API_KEY and API_SECRET.

In this "new" method Coinkite's server is querying the **Ledger Server** via Ledger API.  But this code is completely closed source, and uses a different derivation path than the "old method"

>>There is no redundancy. Coinkite provides a full UTXO report, and if their service disappears I could still manually retrieve my funds.
>>With your the "old" method, I could use the btchip-c-api / python-api / bitmex scripts and offline co-sign the transaction.

>you can still do that. Absolutely nothing has changed. When using the command line tools you just need to start the derivation from the path we arbitrary chose in https://github.com/LedgerHQ/ledger-wallet-chrome/blob/master/app/src/utils/apps/coinkite.coffee (0xb11e'/0xccc0') or 45342h/52416h if using a different notation. Exactly the same as before.

Using the BitMEX scripts and the above derivation path, and 1.4.xx firmware with winUSB, I was able make the equivalent offline signature as with the "old" Ledger Coinkite App.

`$ python utils/getKey.py 45342h/52416h`
`Path: 45342'/52416'`
`XPUB: xpub = same as Ledger Coinkite App`

`$ vi settings.py`
`KEYPATH_BASE="45342'/52416'"`
`COINKITE_API_KEY="fill this in"`
`COINKITE_API_SECRET="fill this in"`
`COINKITE_USER_REF="fill this in"`

Downloading the coinkite sign-xxxx.json

`$ python signTxCoinkiteJSON.py sign-xxxx.json`
`....`
`Output written to output-yyyy.json`

This file can be uploaded to CK to complete the cosign.

>>With this "new" method, if a future Chrome update breaks something, or if Ledger's home server goes offline then it will be impossible to cosign. A single point of failure. How could I trust my life's savings on the uptime of Ledger's server ? This is even worse than case wallet's multisig.

>I think you'll revise this considering what I said before

>Besides, the old application didn't change anything there - it was still bound to the wallet, and couldn't start if you couldn't open the wallet.

>>At least Trezor is not dependent on myTrezor (who's BoP server crashes intermittently). One can still use mycelium/electrum or a BIP32 calculator to retrieve my funds.

>You can do exactly the same here.

>Of course if you lock funds in a multisignature then all parties need to collaborate.

With this "new" method, both CK and Ledger's server need to be online.  With the "old" method only CK's server was needed.  Today already we have seen both [greenaddress](https://bitcointalk.org/index.php?topic=521988.msg11672435#msg11672435) and [myTrezor](https://bitcointalk.org/index.php?topic=122438.msg11664632#msg11664632) go down

Coinkite multisig offers Download/Upload of the .json file for ledger's "new" method as backup.

Can you provide the Path Derivation this "new" method uses when CK queries Ledger's API, so that I can generate a BitMEX signed output .json ?

At the moment this would only work for me on old firmware, but I'll see if David's tips get the python and c tools working for unified HIDAPI firmware.

**Comment by aussiehash** [comment]
Thanks Nicolas for all the help

To cosign the "old" method with BitMEX 

    $ vi settings.py
    KEYPATH_BASE="45342'/52416'"

To cosign the "new" method with BitMEX

    $ vi settings.py
    KEYPATH_BASE="45342'/52416'/1"

**Comment by btchip** [comment]
likewise, thanks for the tests. I'll send a PR soon to BitMEX to fix this properly.

**Comment by EricLarch** [comment]
For information, you can still launch the Coinkite app by going in the console:
`ledger.app.router.go("/apps/coinkite/dashboard/index")`

**Comment by aussiehash** [comment]
>For information, you can still launch the Coinkite app by going in the console:
>ledger.app.router.go("/apps/coinkite/dashboard/index")

I can **only** access :  `Right Click > Inspect Element > Console` If I have manually downloaded the .crx, unzipped it, then manually added with unpacked extension to Chrome.

If I either download the Ledger Chrome Wallet from Google Play, or Drag'n'Drop install the .crx release, then Right Click is disabled.

In both cases, the hotkey for JavaScript Console doesn't work in the Chrome App, but does work normally in a browser window.

**Comment by EricLarch** [comment]
Just go to chrome://extensions to launch the console on the
view/layout.html

**Comment by aussiehash** [comment]
Thanks -- found the views/layout.html button.

https://medium.com/@Ledger/implementing-a-trustless-security-solution-with-hardware-wallets-and-multisignature-8f50732c6f4c

>With the integration of the Ledger API by Coinkite, it is now possible in just a few clicks to build a very secure and trustless 2 of 2 multisignature wallet. Each key is secured by a Ledger Nano (or Ledger HW1), and the transaction logic is managed seamlessly by Coinkite’s interface.

>**In case of a disaster (Ledger and/or Coinkite goes out of business), you can recover your bitcoins using BIP39 backups and some scripting tools.**

At the moment this is only partially true, With the BitMEX scripts and the correct derivation paths, one can now cosign from the command line the Coinkite JSON files, for the CK "Hardware wallet" method and the CK "Import Key" xpub method.

However Ledger Chrome Wallet requires 1.01 unified firmware, paired to a 2nd factor security card, and the BitMEX scripts are expecting the HID keyboard replay 2nd factor.  Attempting to BitMEX JSON script sign 1.01 firmware fails, getting stuck at [use2FA=True](https://github.com/BitMEX/btchip-signing-tools/blob/master/signMessage.py#L24), but works with old 1.4.1x firmware.

Also Coinkite does not supply any scripts to generate a manual transaction from their **Full UTXO report**, so if Coinkite goes out of business you could not guarantee retrieval transaction of your multisig funds.
